version: "3"
networks:
  expense:
volumes:
  mysql: #docker volume create mysql
services:
  mysql:
    image: govi06/mysql:v1
    container_name: mysql
    volumes:
    - mysql /var/lib/mysql  # -v mysql:/var/lib/mysql
  backend:
    image: govi06/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: govi06/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend

